export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_FLOW_DETAILS = 'SET_FLOW_DETAILS';
export const SET_TRANSACTION_DETAILS = 'SET_TRANSACTION_DETAILS';
export const SET_EXPORT_DATA = 'SET_EXPORT_DATA';